### ISSUE TITLE
Issue with file latest.csv

### ISSUE THREAD

**Issue by Pratigyapatidar** [AnujSharma56/FASYS#1]
I am facing issue to excessing code . Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\prati\anaconda3\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "C:/projectCode/FASYS-master/G1.py", line 40, in update_button
    scan_faces(kfe, kfn,int(entry_1u.get()))
  File "C:\projectCode\FASYS-master\pro_face_recog\run.py", line 141, in scan_faces
    store_latest_values(df)
  File "C:\projectCode\FASYS-master\pro_face_recog\run.py", line 150, in store_latest_values
    df.to_csv('latest.csv', index=False)
  File "C:\Users\prati\anaconda3\lib\site-packages\pandas\core\generic.py", line 3204, in to_csv
    formatter.save()
  File "C:\Users\prati\anaconda3\lib\site-packages\pandas\io\formats\csvs.py", line 184, in save
    f, handles = get_handle(
  File "C:\Users\prati\anaconda3\lib\site-packages\pandas\io\common.py", line 428, in get_handle
    f = open(path_or_buf, mode, encoding=encoding, newline="")
PermissionError: [Errno 13] Permission denied: 'latest.csv'
[ WARN:1] global C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-wwma2wne\opencv\modules\videoio\src\cap_msmf.cpp (435) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback.

Please help to resolve it.

**Comment by Pratigyapatidar** [comment]
This one is solve .
